from __future__ import annotations

import hashlib
import json
import shlex
from dataclasses import asdict
from pathlib import Path
from typing import Any

from .ci_config import QualityCIConfig


def _workflow_header(config: QualityCIConfig) -> str:
    payload = json.dumps(asdict(config), sort_keys=True, separators=(",", ":"))
    digest = hashlib.sha256(payload.encode("utf-8")).hexdigest()[:16]
    return (
        "# Generated by AgentKit. Re-run `agentkit ci quality install` to refresh.\n"
        f"# agentkit-quality-config-sha256: {digest}\n"
    )


def render_quality_workflow(config: QualityCIConfig) -> str:
    cache_line = "          cache: pip\n" if config.cache_enabled else ""
    quality_cache_step = ""
    if config.cache_enabled:
        quality_cache_step = """      - name: Restore AgentKit quality cache
        uses: actions/cache@v4
        with:
          path: .agent/cache
          key: agentkit-quality-${{ runner.os }}-${{ hashFiles('.agent/agentkit.toml', '.strictacode.yml', '.strictacode.yaml', '.strictacode.json') }}
          restore-keys: |
            agentkit-quality-${{ runner.os }}-

"""
    annotations_flag = " --annotations" if config.annotations else ""
    package_spec = shlex.quote(config.package_spec)
    python_version = json.dumps(config.python_version)
    base_branch = shlex.quote(config.base_branch)

    return _workflow_header(config) + f'''name: AgentKit Quality

on:
  pull_request:
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: agentkit-quality-${{{{ github.workflow }}}}-${{{{ github.ref }}}}
  cancel-in-progress: true

jobs:
  quality:
    name: quality
    runs-on: ubuntu-latest
    timeout-minutes: 30
    env:
      AGENTKIT_CI_RUN_ID: github-${{{{ github.run_id }}}}-${{{{ github.run_attempt }}}}

    steps:
      - name: Checkout full history
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: {python_version}
{cache_line}
{quality_cache_step}      - name: Install AgentKit quality support
        run: |
          python -m pip install --upgrade pip
          python -m pip install {package_spec}

      - name: Validate AgentKit quality configuration
        run: agentkit ci quality validate

      - name: Run merge-base quality comparison
        id: quality
        continue-on-error: true
        shell: bash
        run: |
          DEFAULT_BASE={base_branch}
          BASE_NAME="${{GITHUB_BASE_REF:-$DEFAULT_BASE}}"
          BASE_REF="origin/$BASE_NAME"
          agentkit ci quality run-local \\
            --base-ref "$BASE_REF" \\
            --run-id "$AGENTKIT_CI_RUN_ID"

      - name: Publish AgentKit job summary
        if: always()
        shell: bash
        run: |
          agentkit ci quality summary \\
            --run-id "$AGENTKIT_CI_RUN_ID" \\
            --output "$GITHUB_STEP_SUMMARY" --append{annotations_flag}

      - name: Upload AgentKit quality artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: agentkit-quality-${{{{ github.run_id }}}}-${{{{ github.run_attempt }}}}
          path: .agent/state/runs/${{{{ env.AGENTKIT_CI_RUN_ID }}}}/ci-artifacts
          if-no-files-found: error
          retention-days: {config.artifact_retention_days}

      - name: Enforce AgentKit quality result
        if: always()
        shell: bash
        run: |
          EXIT_FILE=".agent/state/runs/$AGENTKIT_CI_RUN_ID/ci-exit-code"
          if [[ ! -f "$EXIT_FILE" ]]; then
            echo "AgentKit did not produce ci-exit-code" >&2
            exit 2
          fi
          exit "$(cat "$EXIT_FILE")"
'''


def workflow_path(project_root: Path, config: QualityCIConfig) -> Path:
    return project_root / config.workflow_path


def install_quality_workflow(
    project_root: Path,
    config: QualityCIConfig,
    *,
    force: bool = False,
) -> tuple[Path, bool]:
    path = workflow_path(project_root, config)
    content = render_quality_workflow(config)
    if path.is_file():
        existing = path.read_text(encoding="utf-8")
        if existing == content:
            return path, False
        if not force:
            raise RuntimeError(
                f"{path} already exists and differs from the generated workflow; "
                "rerun with --force only after reviewing the diff"
            )
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content, encoding="utf-8")
    return path, True


def preview_quality_workflow(
    project_root: Path,
    config: QualityCIConfig,
) -> dict[str, Any]:
    path = workflow_path(project_root, config)
    generated = render_quality_workflow(config)
    existing = path.read_text(encoding="utf-8") if path.is_file() else None
    return {
        "path": str(path),
        "exists": existing is not None,
        "matches_generated": existing == generated if existing is not None else False,
        "would_overwrite": existing is not None and existing != generated,
        "content": generated,
    }
