from __future__ import annotations

import os
import shutil
import sysconfig
from pathlib import Path

from .builtin import BUILTIN_AGENT_MD, CORE_SKILLS, render_core_skill
from .config import write_default_config
from .graphify import install_graphify_project_skill


MAKEFILE_AGENT = r"""# Generated by AgentKit. Project Makefile should include this file.
AGENTKIT ?= agentkit
AGENT ?=
MODE ?= auto
TASK ?=
TASK_FILE ?=
RUN_ID ?=
REPORT_LIMIT ?= 20
CONTEXT_PHASE ?= implementation
CONTEXT_OUTPUT ?=
CACHE_LIMIT ?= 20
CACHE_NAMESPACE ?=
CACHE_MAX_AGE_DAYS ?= 30
MODEL_ROUTE ?=
MODEL_PHASE ?=
MODEL_PROVIDER ?= openai
PROVIDER_LIVE ?= 0
GRAPHIFY_PLATFORM ?= agents

.PHONY: ai ai-plan ai-graph ai-graph-install ai-check ai-doctor ai-status ai-usage ai-budget ai-report ai-telemetry ai-context ai-profile ai-profile-refresh ai-cache-stats ai-cache-list ai-cache-prune ai-cache-clear ai-context-maintain ai-model-doctor ai-models ai-route ai-provider-test ai-upgrade-check ai-migrate ai-self-test ai-diagnostics ai-release-check

ai:
	$(AGENTKIT) run $(if $(MODEL_ROUTE),--route "$(MODEL_ROUTE)",$(if $(AGENT),--agent "$(AGENT)",)) --mode "$(MODE)" $(if $(TASK),--task "$(TASK)",) $(if $(TASK_FILE),--task-file "$(TASK_FILE)",)

ai-plan:
	$(AGENTKIT) plan $(if $(MODEL_ROUTE),--route "$(MODEL_ROUTE)",$(if $(AGENT),--agent "$(AGENT)",)) --mode "$(MODE)" $(if $(TASK),--task "$(TASK)",) $(if $(TASK_FILE),--task-file "$(TASK_FILE)",)

ai-graph:
	$(AGENTKIT) graph update

ai-graph-install:
	$(AGENTKIT) graph install --platform "$(GRAPHIFY_PLATFORM)"

ai-check:
	$(AGENTKIT) check

ai-doctor:
	$(AGENTKIT) doctor

ai-status:
	$(AGENTKIT) status

ai-usage:
	$(AGENTKIT) usage $(if $(RUN_ID),--run-id "$(RUN_ID)",)

ai-budget:
	$(AGENTKIT) budget $(if $(RUN_ID),--run-id "$(RUN_ID)",)

ai-report:
	$(AGENTKIT) report --limit "$(REPORT_LIMIT)"

ai-telemetry: ai-usage ai-budget

ai-context:
	$(AGENTKIT) context compile --phase "$(CONTEXT_PHASE)" --mode "$(MODE)" $(if $(TASK),--task "$(TASK)",) $(if $(TASK_FILE),--task-file "$(TASK_FILE)",) $(if $(CONTEXT_OUTPUT),--output "$(CONTEXT_OUTPUT)",)

ai-profile:
	$(AGENTKIT) profile show

ai-profile-refresh:
	$(AGENTKIT) profile refresh

ai-cache-stats:
	$(AGENTKIT) cache stats

ai-cache-list:
	$(AGENTKIT) cache list --limit "$(CACHE_LIMIT)" $(if $(CACHE_NAMESPACE),--namespace "$(CACHE_NAMESPACE)",)

ai-cache-prune:
	$(AGENTKIT) cache prune --max-age-days "$(CACHE_MAX_AGE_DAYS)"

ai-cache-clear:
	$(AGENTKIT) cache clear --yes

ai-context-maintain: ai-profile-refresh ai-cache-prune ai-cache-stats

ai-model-doctor:
	$(AGENTKIT) models doctor

ai-models:
	$(AGENTKIT) models list

ai-route:
	$(AGENTKIT) models route $(if $(MODEL_PHASE),--phase "$(MODEL_PHASE)",) $(if $(MODEL_ROUTE),--route "$(MODEL_ROUTE)",) $(if $(TASK),--task "$(TASK)",)

ai-provider-test:
	$(AGENTKIT) providers test "$(MODEL_PROVIDER)" $(if $(filter 1,$(PROVIDER_LIVE)),--live,)

# BEGIN AGENTKIT RELEASE
.PHONY: ai-upgrade-check ai-migrate ai-self-test ai-diagnostics ai-release-check

ai-upgrade-check:
	$(AGENTKIT) migrate check

ai-migrate:
	$(AGENTKIT) migrate apply

ai-self-test:
	$(AGENTKIT) self-test

ai-diagnostics:
	$(AGENTKIT) diagnostics bundle

ai-release-check: ai-upgrade-check ai-self-test
# END AGENTKIT RELEASE
"""

_INCLUDE_BLOCK = """
# BEGIN AGENTKIT
-include .agent/Makefile.agent
# END AGENTKIT
"""
_GITIGNORE_BLOCK = """
# BEGIN AGENTKIT
graphify-out/
.agent/state/
.agent/cache/
.agent/evals/
.agent/backups/
.agent/diagnostics/
.agent/update-candidates/
.agent/worktrees/
.agent/project-profile.json
# END AGENTKIT
"""


def _source_kit_root() -> Path | None:
    candidates: list[Path] = [Path(sysconfig.get_path("data")) / "share" / "agentkit"]
    env = os.environ.get("AGENTKIT_SOURCE")
    if env:
        candidates.append(Path(env).expanduser())
    module_path = Path(__file__).resolve()
    candidates.extend(module_path.parents)
    for candidate in candidates:
        if (
            (candidate / "AGENT.md").is_file()
            and (candidate / "skills").is_dir()
        ):
            return candidate
    return None


def _copy_file(source: Path, target: Path, *, force: bool) -> None:
    if source.is_symlink():
        raise ValueError(f"Refusing to install symlinked AgentKit resource: {source}")
    if force or not target.exists():
        target.parent.mkdir(parents=True, exist_ok=True)
        shutil.copy2(source, target)


def _copy_full_kit(source: Path, target: Path, *, force: bool = False) -> None:
    _copy_file(source / "AGENT.md", target / "AGENT.md", force=force)
    for directory in ("skills", "policies", "schemas", "templates"):
        src = source / directory
        if src.is_dir():
            for path in src.rglob("*"):
                if path.is_file() and not path.is_symlink():
                    _copy_file(
                        path,
                        target / path.relative_to(source),
                        force=force,
                    )


def _write_builtin_kit(target: Path, *, force: bool = False) -> None:
    agent_md = target / "AGENT.md"
    if force or not agent_md.exists():
        agent_md.write_text(BUILTIN_AGENT_MD, encoding="utf-8")
    for name in CORE_SKILLS:
        path = target / "skills" / name / "SKILL.md"
        if force or not path.exists():
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(render_core_skill(name), encoding="utf-8")


def _append_once(path: Path, block: str, marker: str) -> None:
    existing = path.read_text(encoding="utf-8") if path.exists() else ""
    end_marker = "# END AGENTKIT"
    if marker in existing and marker == "# BEGIN AGENTKIT" and end_marker in existing:
        start = existing.index(marker)
        end = existing.index(end_marker, start) + len(end_marker)
        replacement = block.strip()
        updated = existing[:start] + replacement + existing[end:]
        path.write_text(updated, encoding="utf-8")
    elif marker not in existing:
        path.write_text(existing.rstrip() + block, encoding="utf-8")


def initialize_project(
    project_root: Path,
    *,
    force: bool = False,
    platform: str = "agents",
    install_graphify_skill: bool = True,
) -> dict[str, object]:
    agent_dir = project_root / ".agent"
    agent_dir.mkdir(parents=True, exist_ok=True)
    source = _source_kit_root()
    if source:
        _copy_full_kit(source, agent_dir, force=force)
        resource_mode = "full-source-kit"
    else:
        _write_builtin_kit(agent_dir, force=force)
        resource_mode = "embedded-core-kit"

    config_path = write_default_config(project_root, force=force)
    makefile_agent = agent_dir / "Makefile.agent"
    if force or not makefile_agent.exists():
        makefile_agent.write_text(MAKEFILE_AGENT, encoding="utf-8")
    _append_once(
        project_root / "Makefile",
        _INCLUDE_BLOCK,
        "# BEGIN AGENTKIT",
    )
    _append_once(
        project_root / ".gitignore",
        _GITIGNORE_BLOCK,
        "# BEGIN AGENTKIT",
    )

    graphify_install = (
        install_graphify_project_skill(
            project_root,
            platform=platform,
            required=False,
        )
        if install_graphify_skill
        else {
            "attempted": False,
            "installed": False,
            "platform": platform,
            "reason": "disabled",
            "repair_command": f"agentkit graph install --platform {platform}",
        }
    )
    return {
        "project_root": str(project_root),
        "resource_mode": resource_mode,
        "config": str(config_path),
        "makefile": str(makefile_agent),
        "graphify_skill_install": graphify_install,
    }
