from __future__ import annotations

import os
import shutil
import subprocess
from pathlib import Path

from .builtin import BUILTIN_AGENT_MD, CORE_SKILLS, render_core_skill
from .config import write_default_config


MAKEFILE_AGENT = r"""# Generated by AgentKit. Project Makefile should include this file.
AGENTKIT ?= agentkit
AGENT ?= codex
MODE ?= auto
TASK ?=
TASK_FILE ?=
RUN_ID ?=
REPORT_LIMIT ?= 20
CONTEXT_PHASE ?= implementation
CONTEXT_OUTPUT ?=
CACHE_LIMIT ?= 20
CACHE_NAMESPACE ?=
CACHE_MAX_AGE_DAYS ?= 30

.PHONY: ai ai-plan ai-graph ai-check ai-doctor ai-status ai-usage ai-budget ai-report ai-telemetry ai-context ai-profile ai-profile-refresh ai-cache-stats ai-cache-list ai-cache-prune ai-cache-clear ai-context-maintain

ai:
	$(AGENTKIT) run --agent "$(AGENT)" --mode "$(MODE)" $(if $(TASK),--task "$(TASK)",) $(if $(TASK_FILE),--task-file "$(TASK_FILE)",)

ai-plan:
	$(AGENTKIT) plan --agent "$(AGENT)" --mode "$(MODE)" $(if $(TASK),--task "$(TASK)",) $(if $(TASK_FILE),--task-file "$(TASK_FILE)",)

ai-graph:
	$(AGENTKIT) graph update

ai-check:
	$(AGENTKIT) check

ai-doctor:
	$(AGENTKIT) doctor

ai-status:
	$(AGENTKIT) status

ai-usage:
	$(AGENTKIT) usage $(if $(RUN_ID),--run-id "$(RUN_ID)",)

ai-budget:
	$(AGENTKIT) budget $(if $(RUN_ID),--run-id "$(RUN_ID)",)

ai-report:
	$(AGENTKIT) report --limit "$(REPORT_LIMIT)"

ai-telemetry: ai-usage ai-budget

ai-context:
	$(AGENTKIT) context compile --phase "$(CONTEXT_PHASE)" --mode "$(MODE)" $(if $(TASK),--task "$(TASK)",) $(if $(TASK_FILE),--task-file "$(TASK_FILE)",) $(if $(CONTEXT_OUTPUT),--output "$(CONTEXT_OUTPUT)",)

ai-profile:
	$(AGENTKIT) profile show

ai-profile-refresh:
	$(AGENTKIT) profile refresh

ai-cache-stats:
	$(AGENTKIT) cache stats

ai-cache-list:
	$(AGENTKIT) cache list --limit "$(CACHE_LIMIT)" $(if $(CACHE_NAMESPACE),--namespace "$(CACHE_NAMESPACE)",)

ai-cache-prune:
	$(AGENTKIT) cache prune --max-age-days "$(CACHE_MAX_AGE_DAYS)"

ai-cache-clear:
	$(AGENTKIT) cache clear --yes

ai-context-maintain: ai-profile-refresh ai-cache-prune ai-cache-stats
"""

_INCLUDE_BLOCK = """
# BEGIN AGENTKIT
-include .agent/Makefile.agent
# END AGENTKIT
"""
_GITIGNORE_BLOCK = """
# BEGIN AGENTKIT
graphify-out/
.agent/state/
.agent/cache/
.agent/evals/
.agent/project-profile.json
# END AGENTKIT
"""


def _source_kit_root() -> Path | None:
    candidates: list[Path] = []
    env = os.environ.get("AGENTKIT_SOURCE")
    if env:
        candidates.append(Path(env).expanduser())
    module_path = Path(__file__).resolve()
    candidates.extend(module_path.parents)
    for candidate in candidates:
        if (
            (candidate / "AGENT.md").is_file()
            and (candidate / "skills").is_dir()
        ):
            return candidate
    return None


def _copy_full_kit(source: Path, target: Path) -> None:
    shutil.copy2(source / "AGENT.md", target / "AGENT.md")
    for directory in ("skills", "policies", "schemas", "templates"):
        src = source / directory
        if src.is_dir():
            shutil.copytree(src, target / directory, dirs_exist_ok=True)


def _write_builtin_kit(target: Path) -> None:
    (target / "AGENT.md").write_text(
        BUILTIN_AGENT_MD,
        encoding="utf-8",
    )
    for name in CORE_SKILLS:
        path = target / "skills" / name / "SKILL.md"
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(render_core_skill(name), encoding="utf-8")


def _append_once(path: Path, block: str, marker: str) -> None:
    existing = path.read_text(encoding="utf-8") if path.exists() else ""
    if marker not in existing:
        path.write_text(existing.rstrip() + block, encoding="utf-8")


def initialize_project(
    project_root: Path,
    *,
    force: bool = False,
    platform: str = "agents",
    install_graphify_skill: bool = True,
) -> dict[str, object]:
    agent_dir = project_root / ".agent"
    agent_dir.mkdir(parents=True, exist_ok=True)
    source = _source_kit_root()
    if source:
        _copy_full_kit(source, agent_dir)
        resource_mode = "full-source-kit"
    else:
        _write_builtin_kit(agent_dir)
        resource_mode = "embedded-core-kit"

    config_path = write_default_config(project_root, force=force)
    makefile_agent = agent_dir / "Makefile.agent"
    if force or not makefile_agent.exists():
        makefile_agent.write_text(MAKEFILE_AGENT, encoding="utf-8")
    _append_once(
        project_root / "Makefile",
        _INCLUDE_BLOCK,
        "# BEGIN AGENTKIT",
    )
    _append_once(
        project_root / ".gitignore",
        _GITIGNORE_BLOCK,
        "# BEGIN AGENTKIT",
    )

    graphify_install: dict[str, object]
    if install_graphify_skill and shutil.which("graphify"):
        result = subprocess.run(
            ["graphify", "install", "--project", "--platform", platform],
            cwd=project_root,
            text=True,
            capture_output=True,
            check=False,
            stdin=subprocess.DEVNULL,
        )
        graphify_install = {
            "attempted": True,
            "platform": platform,
            "returncode": result.returncode,
            "stdout": result.stdout.strip(),
            "stderr": result.stderr.strip(),
        }
    else:
        graphify_install = {
            "attempted": False,
            "platform": platform,
            "reason": (
                "disabled"
                if not install_graphify_skill
                else "graphify executable not found"
            ),
        }
    return {
        "project_root": str(project_root),
        "resource_mode": resource_mode,
        "config": str(config_path),
        "makefile": str(makefile_agent),
        "graphify_skill_install": graphify_install,
    }
